config/routes.rb
Rails.application.routes.draw do

  resource :user

  root 'welcome#index'

  post 'user/sign_in' => 'users#sign_in', as: :sign_in
  get 'user/sign_out' => 'users#sign_out', as: :sign_out

end

app/models/session.rb
class Session < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :login, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params.require(:user).permit!)
    if @user.save
      Session.create(api_key: @user.id)
      session[:api_key] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def sign_in
    if session[:api_key]
      render :sign_in
    else
      login = params[:user][:login]
      email = params[:user][:email]
      password = params[:user][:password_digest]
      @user = User.find_by(login: login, email: email, password_digest: password)
      if @user
        Session.create(api_key: @user.id)
        session[:api_key] = @user.id
        render :sign_in
      end
    end
  end

  def sign_out
    # binding.pry
    session.clear
    redirect_to root_path
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lesson3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<% unless session[:api_key] %>
    <h1>Registration</h1>
    <%= form_for @user, url: user_path do |f| %>
        <p>
          <%= f.label :login %>
          <br/>
          <%= f.text_field :login %>
        </p>
        <p>
          <%= f.label :email %>
          <br/>
          <%= f.text_field :email %>
        </p>
        <p>
          <%= f.label :password %>
          <br/>
          <%= f.password_field :password_digest %>
        </p>
        <p>
          <%= f.label :password_confirmation %>
          <br/>
          <%= f.password_field :password_confirmation %>
        </p>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
        <%= f.submit :OK %>
    <% end %>

    <h2>Sign in</h2>
    <%= form_for @user, url: sign_in_path do |f| %>
        <p>
          <%= f.label :login %>
          <br/>
          <%= f.text_field :login %>
        </p>
        <p>
          <%= f.label :email %>
          <br/>
          <%= f.text_field :email %>
        </p>
        <p>
          <%= f.label :password %>
          <br/>
          <%= f.password_field :password_digest %>
        </p>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
        <%= f.submit :OK %>
    <% end %>
<% else %>
    <h2>You have already signed in</h2>
    <%= link_to "Sign out", sign_out_path %>
<% end %>

app/views/users/sign_in.html.erb
You signed in

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Go to the http://localhost:3000/user/new</p>